import React from 'react'
import './App.css';
import Cats from './components/Cats';
import Header from './components/Header';
import { Canvas } from '@react-three/fiber';
import { Stars } from '@react-three/drei';
import Kiwi from './components/Kiwi';

function App() {
  return (
    <div className='App'>
      <Header />
      <div className="container">
        <Cats />
      </div>
      <div className="container">
        <Canvas style={{heigth: '200px', width: '100%'}}>
          <Stars/>
          <Kiwi/>
        </Canvas>
      </div>
    </div>
  );
}


/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export default function Kiwi({ ...props }) {
//   const group = useRef()
//   const { nodes, materials } = useGLTF('/food_kiwi_01_4k.gltf')
//   return (
//     <group ref={group} {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2,0,0]}>
//         <group rotation={[Math.PI / 2,0,0]}>
//           <group scale={10}>
//             <mesh geometry={nodes.food_kiwi_01.geometry} material={materials.food_kiwi_01} />
//           </group>
//         </group>
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/food_kiwi_01_4k.gltf')

export default App;
